[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait="0.1"
pingora = { version = "0.4.0", features = [ "lb" ] }
log = "0.4"
env_logger = "0.9"
http = "1.1.0"
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
